export type Region = {
  code: string;
  name: string;
  countryCode: 'gb-eng' | 'gb-sct' | 'gb-wls' | 'gb-nir';
};

export const REGIONS: Region[] = [
  // ── England: Two-tier counties ─────────────────────────────────────────────
  { code: 'gb-eng-cam', name: 'Cambridgeshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-cma', name: 'Cumbria', countryCode: 'gb-eng' },
  { code: 'gb-eng-dby', name: 'Derbyshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-dev', name: 'Devon', countryCode: 'gb-eng' },
  { code: 'gb-eng-dor', name: 'Dorset', countryCode: 'gb-eng' },
  { code: 'gb-eng-esx', name: 'East Sussex', countryCode: 'gb-eng' },
  { code: 'gb-eng-ess', name: 'Essex', countryCode: 'gb-eng' },
  { code: 'gb-eng-gls', name: 'Gloucestershire', countryCode: 'gb-eng' },
  { code: 'gb-eng-ham', name: 'Hampshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-hrt', name: 'Hertfordshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-ken', name: 'Kent', countryCode: 'gb-eng' },
  { code: 'gb-eng-lan', name: 'Lancashire', countryCode: 'gb-eng' },
  { code: 'gb-eng-lec', name: 'Leicestershire', countryCode: 'gb-eng' },
  { code: 'gb-eng-lin', name: 'Lincolnshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-nfk', name: 'Norfolk', countryCode: 'gb-eng' },
  { code: 'gb-eng-nyk', name: 'North Yorkshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-ntt', name: 'Nottinghamshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-oxf', name: 'Oxfordshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-som', name: 'Somerset', countryCode: 'gb-eng' },
  { code: 'gb-eng-sts', name: 'Staffordshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-sfk', name: 'Suffolk', countryCode: 'gb-eng' },
  { code: 'gb-eng-sry', name: 'Surrey', countryCode: 'gb-eng' },
  { code: 'gb-eng-war', name: 'Warwickshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-wsx', name: 'West Sussex', countryCode: 'gb-eng' },
  { code: 'gb-eng-wor', name: 'Worcestershire', countryCode: 'gb-eng' },
  // ── England: London ────────────────────────────────────────────────────────
  { code: 'gb-eng-lnd', name: 'London, City of', countryCode: 'gb-eng' },
  { code: 'gb-eng-bdg', name: 'Barking and Dagenham', countryCode: 'gb-eng' },
  { code: 'gb-eng-bne', name: 'Barnet', countryCode: 'gb-eng' },
  { code: 'gb-eng-bex', name: 'Bexley', countryCode: 'gb-eng' },
  { code: 'gb-eng-ben', name: 'Brent', countryCode: 'gb-eng' },
  { code: 'gb-eng-bry', name: 'Bromley', countryCode: 'gb-eng' },
  { code: 'gb-eng-cmd', name: 'Camden', countryCode: 'gb-eng' },
  { code: 'gb-eng-cry', name: 'Croydon', countryCode: 'gb-eng' },
  { code: 'gb-eng-eal', name: 'Ealing', countryCode: 'gb-eng' },
  { code: 'gb-eng-enf', name: 'Enfield', countryCode: 'gb-eng' },
  { code: 'gb-eng-gre', name: 'Greenwich', countryCode: 'gb-eng' },
  { code: 'gb-eng-hck', name: 'Hackney', countryCode: 'gb-eng' },
  { code: 'gb-eng-hmf', name: 'Hammersmith and Fulham', countryCode: 'gb-eng' },
  { code: 'gb-eng-hry', name: 'Haringey', countryCode: 'gb-eng' },
  { code: 'gb-eng-hrw', name: 'Harrow', countryCode: 'gb-eng' },
  { code: 'gb-eng-hav', name: 'Havering', countryCode: 'gb-eng' },
  { code: 'gb-eng-hil', name: 'Hillingdon', countryCode: 'gb-eng' },
  { code: 'gb-eng-hns', name: 'Hounslow', countryCode: 'gb-eng' },
  { code: 'gb-eng-isl', name: 'Islington', countryCode: 'gb-eng' },
  { code: 'gb-eng-kec', name: 'Kensington and Chelsea', countryCode: 'gb-eng' },
  { code: 'gb-eng-ktt', name: 'Kingston upon Thames', countryCode: 'gb-eng' },
  { code: 'gb-eng-lbh', name: 'Lambeth', countryCode: 'gb-eng' },
  { code: 'gb-eng-lew', name: 'Lewisham', countryCode: 'gb-eng' },
  { code: 'gb-eng-mrt', name: 'Merton', countryCode: 'gb-eng' },
  { code: 'gb-eng-nwm', name: 'Newham', countryCode: 'gb-eng' },
  { code: 'gb-eng-rdb', name: 'Redbridge', countryCode: 'gb-eng' },
  { code: 'gb-eng-ric', name: 'Richmond upon Thames', countryCode: 'gb-eng' },
  { code: 'gb-eng-swk', name: 'Southwark', countryCode: 'gb-eng' },
  { code: 'gb-eng-stn', name: 'Sutton', countryCode: 'gb-eng' },
  { code: 'gb-eng-twh', name: 'Tower Hamlets', countryCode: 'gb-eng' },
  { code: 'gb-eng-wft', name: 'Waltham Forest', countryCode: 'gb-eng' },
  { code: 'gb-eng-wnd', name: 'Wandsworth', countryCode: 'gb-eng' },
  { code: 'gb-eng-wsm', name: 'Westminster', countryCode: 'gb-eng' },
  // ── England: Metropolitan districts ───────────────────────────────────────
  { code: 'gb-eng-bns', name: 'Barnsley', countryCode: 'gb-eng' },
  { code: 'gb-eng-bir', name: 'Birmingham', countryCode: 'gb-eng' },
  { code: 'gb-eng-bol', name: 'Bolton', countryCode: 'gb-eng' },
  { code: 'gb-eng-brd', name: 'Bradford', countryCode: 'gb-eng' },
  { code: 'gb-eng-bur', name: 'Bury', countryCode: 'gb-eng' },
  { code: 'gb-eng-cld', name: 'Calderdale', countryCode: 'gb-eng' },
  { code: 'gb-eng-cov', name: 'Coventry', countryCode: 'gb-eng' },
  { code: 'gb-eng-dnc', name: 'Doncaster', countryCode: 'gb-eng' },
  { code: 'gb-eng-dud', name: 'Dudley', countryCode: 'gb-eng' },
  { code: 'gb-eng-gat', name: 'Gateshead', countryCode: 'gb-eng' },
  { code: 'gb-eng-kir', name: 'Kirklees', countryCode: 'gb-eng' },
  { code: 'gb-eng-kwl', name: 'Knowsley', countryCode: 'gb-eng' },
  { code: 'gb-eng-lds', name: 'Leeds', countryCode: 'gb-eng' },
  { code: 'gb-eng-liv', name: 'Liverpool', countryCode: 'gb-eng' },
  { code: 'gb-eng-man', name: 'Manchester', countryCode: 'gb-eng' },
  { code: 'gb-eng-net', name: 'Newcastle upon Tyne', countryCode: 'gb-eng' },
  { code: 'gb-eng-nty', name: 'North Tyneside', countryCode: 'gb-eng' },
  { code: 'gb-eng-old', name: 'Oldham', countryCode: 'gb-eng' },
  { code: 'gb-eng-rch', name: 'Rochdale', countryCode: 'gb-eng' },
  { code: 'gb-eng-rot', name: 'Rotherham', countryCode: 'gb-eng' },
  { code: 'gb-eng-shn', name: 'St. Helens', countryCode: 'gb-eng' },
  { code: 'gb-eng-slf', name: 'Salford', countryCode: 'gb-eng' },
  { code: 'gb-eng-saw', name: 'Sandwell', countryCode: 'gb-eng' },
  { code: 'gb-eng-sft', name: 'Sefton', countryCode: 'gb-eng' },
  { code: 'gb-eng-shf', name: 'Sheffield', countryCode: 'gb-eng' },
  { code: 'gb-eng-sol', name: 'Solihull', countryCode: 'gb-eng' },
  { code: 'gb-eng-sty', name: 'South Tyneside', countryCode: 'gb-eng' },
  { code: 'gb-eng-skp', name: 'Stockport', countryCode: 'gb-eng' },
  { code: 'gb-eng-snd', name: 'Sunderland', countryCode: 'gb-eng' },
  { code: 'gb-eng-tam', name: 'Tameside', countryCode: 'gb-eng' },
  { code: 'gb-eng-trf', name: 'Trafford', countryCode: 'gb-eng' },
  { code: 'gb-eng-wkf', name: 'Wakefield', countryCode: 'gb-eng' },
  { code: 'gb-eng-wll', name: 'Walsall', countryCode: 'gb-eng' },
  { code: 'gb-eng-wgn', name: 'Wigan', countryCode: 'gb-eng' },
  { code: 'gb-eng-wrl', name: 'Wirral', countryCode: 'gb-eng' },
  { code: 'gb-eng-wlv', name: 'Wolverhampton', countryCode: 'gb-eng' },
  // ── England: Unitary authorities ──────────────────────────────────────────
  { code: 'gb-eng-bas', name: 'Bath and North East Somerset', countryCode: 'gb-eng' },
  { code: 'gb-eng-bdf', name: 'Bedford', countryCode: 'gb-eng' },
  { code: 'gb-eng-bbd', name: 'Blackburn with Darwen', countryCode: 'gb-eng' },
  { code: 'gb-eng-bpl', name: 'Blackpool', countryCode: 'gb-eng' },
  { code: 'gb-eng-bcp', name: 'Bournemouth, Christchurch and Poole', countryCode: 'gb-eng' },
  { code: 'gb-eng-brc', name: 'Bracknell Forest', countryCode: 'gb-eng' },
  { code: 'gb-eng-bnh', name: 'Brighton and Hove', countryCode: 'gb-eng' },
  { code: 'gb-eng-bst', name: 'Bristol, City of', countryCode: 'gb-eng' },
  { code: 'gb-eng-bkm', name: 'Buckinghamshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-cbf', name: 'Central Bedfordshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-che', name: 'Cheshire East', countryCode: 'gb-eng' },
  { code: 'gb-eng-chw', name: 'Cheshire West and Chester', countryCode: 'gb-eng' },
  { code: 'gb-eng-con', name: 'Cornwall', countryCode: 'gb-eng' },
  { code: 'gb-eng-dal', name: 'Darlington', countryCode: 'gb-eng' },
  { code: 'gb-eng-der', name: 'Derby', countryCode: 'gb-eng' },
  { code: 'gb-eng-dur', name: 'Durham, County', countryCode: 'gb-eng' },
  { code: 'gb-eng-ery', name: 'East Riding of Yorkshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-hal', name: 'Halton', countryCode: 'gb-eng' },
  { code: 'gb-eng-hpl', name: 'Hartlepool', countryCode: 'gb-eng' },
  { code: 'gb-eng-hef', name: 'Herefordshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-iow', name: 'Isle of Wight', countryCode: 'gb-eng' },
  { code: 'gb-eng-ios', name: 'Isles of Scilly', countryCode: 'gb-eng' },
  { code: 'gb-eng-khl', name: 'Kingston upon Hull', countryCode: 'gb-eng' },
  { code: 'gb-eng-lce', name: 'Leicester', countryCode: 'gb-eng' },
  { code: 'gb-eng-lut', name: 'Luton', countryCode: 'gb-eng' },
  { code: 'gb-eng-mdw', name: 'Medway', countryCode: 'gb-eng' },
  { code: 'gb-eng-mdb', name: 'Middlesbrough', countryCode: 'gb-eng' },
  { code: 'gb-eng-mik', name: 'Milton Keynes', countryCode: 'gb-eng' },
  { code: 'gb-eng-nel', name: 'North East Lincolnshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-nln', name: 'North Lincolnshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-nnh', name: 'North Northamptonshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-nsm', name: 'North Somerset', countryCode: 'gb-eng' },
  { code: 'gb-eng-nbl', name: 'Northumberland', countryCode: 'gb-eng' },
  { code: 'gb-eng-ngm', name: 'Nottingham', countryCode: 'gb-eng' },
  { code: 'gb-eng-pte', name: 'Peterborough', countryCode: 'gb-eng' },
  { code: 'gb-eng-ply', name: 'Plymouth', countryCode: 'gb-eng' },
  { code: 'gb-eng-por', name: 'Portsmouth', countryCode: 'gb-eng' },
  { code: 'gb-eng-rdg', name: 'Reading', countryCode: 'gb-eng' },
  { code: 'gb-eng-rcc', name: 'Redcar and Cleveland', countryCode: 'gb-eng' },
  { code: 'gb-eng-rut', name: 'Rutland', countryCode: 'gb-eng' },
  { code: 'gb-eng-shr', name: 'Shropshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-slg', name: 'Slough', countryCode: 'gb-eng' },
  { code: 'gb-eng-sgc', name: 'South Gloucestershire', countryCode: 'gb-eng' },
  { code: 'gb-eng-sth', name: 'Southampton', countryCode: 'gb-eng' },
  { code: 'gb-eng-sos', name: 'Southend-on-Sea', countryCode: 'gb-eng' },
  { code: 'gb-eng-stt', name: 'Stockton-on-Tees', countryCode: 'gb-eng' },
  { code: 'gb-eng-ste', name: 'Stoke-on-Trent', countryCode: 'gb-eng' },
  { code: 'gb-eng-swd', name: 'Swindon', countryCode: 'gb-eng' },
  { code: 'gb-eng-tfw', name: 'Telford and Wrekin', countryCode: 'gb-eng' },
  { code: 'gb-eng-thr', name: 'Thurrock', countryCode: 'gb-eng' },
  { code: 'gb-eng-tob', name: 'Torbay', countryCode: 'gb-eng' },
  { code: 'gb-eng-wrt', name: 'Warrington', countryCode: 'gb-eng' },
  { code: 'gb-eng-wbk', name: 'West Berkshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-wnh', name: 'West Northamptonshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-wil', name: 'Wiltshire', countryCode: 'gb-eng' },
  { code: 'gb-eng-wnm', name: 'Windsor and Maidenhead', countryCode: 'gb-eng' },
  { code: 'gb-eng-wok', name: 'Wokingham', countryCode: 'gb-eng' },
  { code: 'gb-eng-yor', name: 'York', countryCode: 'gb-eng' },
  // ── Northern Ireland — single network code ─────────────────────────────────
  { code: 'ioi', name: 'Island of Ireland', countryCode: 'gb-nir' },
  // ── Scotland — community short codes (not ISO hierarchical) ────────────────
  { code: 'sco', name: 'Scotland', countryCode: 'gb-sct' },
  { code: 'cen', name: 'Central Scotland', countryCode: 'gb-sct' },
  { code: 'fif', name: 'Fife', countryCode: 'gb-sct' },
  { code: 'tay', name: 'Tayside', countryCode: 'gb-sct' },
  { code: 'gla', name: 'Glasgow area', countryCode: 'gb-sct' },
  { code: 'edi', name: 'Edinburgh area', countryCode: 'gb-sct' },
  { code: 'fal', name: 'Falkirk area', countryCode: 'gb-sct' },
  { code: 'dun', name: 'Dundee area', countryCode: 'gb-sct' },
  { code: 'per', name: 'Perth area', countryCode: 'gb-sct' },
  // ── Wales ──────────────────────────────────────────────────────────────────
  { code: 'gb-wls-bgw', name: 'Blaenau Gwent', countryCode: 'gb-wls' },
  { code: 'gb-wls-bge', name: 'Bridgend', countryCode: 'gb-wls' },
  { code: 'gb-wls-cay', name: 'Caerphilly', countryCode: 'gb-wls' },
  { code: 'gb-wls-crf', name: 'Cardiff', countryCode: 'gb-wls' },
  { code: 'gb-wls-cmn', name: 'Carmarthenshire', countryCode: 'gb-wls' },
  { code: 'gb-wls-cgn', name: 'Ceredigion', countryCode: 'gb-wls' },
  { code: 'gb-wls-cwy', name: 'Conwy', countryCode: 'gb-wls' },
  { code: 'gb-wls-den', name: 'Denbighshire', countryCode: 'gb-wls' },
  { code: 'gb-wls-fln', name: 'Flintshire', countryCode: 'gb-wls' },
  { code: 'gb-wls-gwn', name: 'Gwynedd', countryCode: 'gb-wls' },
  { code: 'gb-wls-agy', name: 'Isle of Anglesey', countryCode: 'gb-wls' },
  { code: 'gb-wls-mty', name: 'Merthyr Tydfil', countryCode: 'gb-wls' },
  { code: 'gb-wls-mon', name: 'Monmouthshire', countryCode: 'gb-wls' },
  { code: 'gb-wls-ntl', name: 'Neath Port Talbot', countryCode: 'gb-wls' },
  { code: 'gb-wls-nwp', name: 'Newport', countryCode: 'gb-wls' },
  { code: 'gb-wls-pem', name: 'Pembrokeshire', countryCode: 'gb-wls' },
  { code: 'gb-wls-pow', name: 'Powys', countryCode: 'gb-wls' },
  { code: 'gb-wls-rct', name: 'Rhondda Cynon Taf', countryCode: 'gb-wls' },
  { code: 'gb-wls-swa', name: 'Swansea', countryCode: 'gb-wls' },
  { code: 'gb-wls-tof', name: 'Torfaen', countryCode: 'gb-wls' },
  { code: 'gb-wls-vgl', name: 'Vale of Glamorgan', countryCode: 'gb-wls' },
  { code: 'gb-wls-wrx', name: 'Wrexham', countryCode: 'gb-wls' },
];

// City / town → region code aliases for search.
// Each entry maps a well-known place name to its containing region.
// Constituent country codes and their current MeshCore network aliases are included here
// so they appear in search results alongside subdivision codes.
export const CITY_ALIASES: { city: string; regionCode: string }[] = [
  // Scotland network code + common aliases
  { city: 'sco',             regionCode: 'sco' },
  { city: 'Scotland',        regionCode: 'sco' },
  // IOI — used by NI and as IOI peering in Scotland
  { city: 'ioi',             regionCode: 'ioi' },
  { city: 'Northern Ireland', regionCode: 'ioi' },
  { city: 'England',           regionCode: 'gb-eng' },
  { city: 'Wales',             regionCode: 'gb-wls' },
  // ── England: Cambridge area ────────────────────────────────────────────────
  { city: 'Cambridge', regionCode: 'gb-eng-cam' },
  { city: 'Ely', regionCode: 'gb-eng-cam' },
  { city: 'Huntingdon', regionCode: 'gb-eng-cam' },
  { city: 'St Ives', regionCode: 'gb-eng-cam' },
  { city: 'Wisbech', regionCode: 'gb-eng-cam' },
  // ── England: Cumbria ──────────────────────────────────────────────────────
  { city: 'Carlisle', regionCode: 'gb-eng-cma' },
  { city: 'Barrow-in-Furness', regionCode: 'gb-eng-cma' },
  { city: 'Kendal', regionCode: 'gb-eng-cma' },
  { city: 'Workington', regionCode: 'gb-eng-cma' },
  { city: 'Whitehaven', regionCode: 'gb-eng-cma' },
  { city: 'Penrith', regionCode: 'gb-eng-cma' },
  // ── England: Derbyshire ───────────────────────────────────────────────────
  { city: 'Chesterfield', regionCode: 'gb-eng-dby' },
  { city: 'Matlock', regionCode: 'gb-eng-dby' },
  { city: 'Buxton', regionCode: 'gb-eng-dby' },
  { city: 'Glossop', regionCode: 'gb-eng-dby' },
  { city: 'Ilkeston', regionCode: 'gb-eng-dby' },
  // ── England: Devon ────────────────────────────────────────────────────────
  { city: 'Exeter', regionCode: 'gb-eng-dev' },
  { city: 'Barnstaple', regionCode: 'gb-eng-dev' },
  { city: 'Newton Abbot', regionCode: 'gb-eng-dev' },
  { city: 'Totnes', regionCode: 'gb-eng-dev' },
  { city: 'Tiverton', regionCode: 'gb-eng-dev' },
  { city: 'Okehampton', regionCode: 'gb-eng-dev' },
  // ── England: Dorset ───────────────────────────────────────────────────────
  { city: 'Dorchester', regionCode: 'gb-eng-dor' },
  { city: 'Weymouth', regionCode: 'gb-eng-dor' },
  { city: 'Blandford Forum', regionCode: 'gb-eng-dor' },
  { city: 'Sherborne', regionCode: 'gb-eng-dor' },
  // ── England: East Sussex ──────────────────────────────────────────────────
  { city: 'Eastbourne', regionCode: 'gb-eng-esx' },
  { city: 'Hastings', regionCode: 'gb-eng-esx' },
  { city: 'Lewes', regionCode: 'gb-eng-esx' },
  { city: 'Bexhill', regionCode: 'gb-eng-esx' },
  { city: 'Uckfield', regionCode: 'gb-eng-esx' },
  // ── England: Essex ────────────────────────────────────────────────────────
  { city: 'Colchester', regionCode: 'gb-eng-ess' },
  { city: 'Chelmsford', regionCode: 'gb-eng-ess' },
  { city: 'Basildon', regionCode: 'gb-eng-ess' },
  { city: 'Harlow', regionCode: 'gb-eng-ess' },
  { city: 'Brentwood', regionCode: 'gb-eng-ess' },
  { city: 'Clacton-on-Sea', regionCode: 'gb-eng-ess' },
  { city: 'Braintree', regionCode: 'gb-eng-ess' },
  { city: 'Witham', regionCode: 'gb-eng-ess' },
  // ── England: Gloucestershire ──────────────────────────────────────────────
  { city: 'Gloucester', regionCode: 'gb-eng-gls' },
  { city: 'Cheltenham', regionCode: 'gb-eng-gls' },
  { city: 'Cirencester', regionCode: 'gb-eng-gls' },
  { city: 'Stroud', regionCode: 'gb-eng-gls' },
  { city: 'Tewkesbury', regionCode: 'gb-eng-gls' },
  // ── England: Hampshire ────────────────────────────────────────────────────
  { city: 'Basingstoke', regionCode: 'gb-eng-ham' },
  { city: 'Winchester', regionCode: 'gb-eng-ham' },
  { city: 'Andover', regionCode: 'gb-eng-ham' },
  { city: 'Eastleigh', regionCode: 'gb-eng-ham' },
  { city: 'Fareham', regionCode: 'gb-eng-ham' },
  { city: 'Gosport', regionCode: 'gb-eng-ham' },
  { city: 'Aldershot', regionCode: 'gb-eng-ham' },
  { city: 'Fleet', regionCode: 'gb-eng-ham' },
  { city: 'Farnborough', regionCode: 'gb-eng-ham' },
  // ── England: Hertfordshire ────────────────────────────────────────────────
  { city: 'Hertford', regionCode: 'gb-eng-hrt' },
  { city: 'Watford', regionCode: 'gb-eng-hrt' },
  { city: 'St Albans', regionCode: 'gb-eng-hrt' },
  { city: 'Stevenage', regionCode: 'gb-eng-hrt' },
  { city: 'Hemel Hempstead', regionCode: 'gb-eng-hrt' },
  { city: 'Welwyn Garden City', regionCode: 'gb-eng-hrt' },
  { city: 'Hatfield', regionCode: 'gb-eng-hrt' },
  { city: 'Letchworth', regionCode: 'gb-eng-hrt' },
  { city: 'Hitchin', regionCode: 'gb-eng-hrt' },
  { city: 'Bishops Stortford', regionCode: 'gb-eng-hrt' },
  // ── England: Kent ─────────────────────────────────────────────────────────
  { city: 'Canterbury', regionCode: 'gb-eng-ken' },
  { city: 'Maidstone', regionCode: 'gb-eng-ken' },
  { city: 'Tunbridge Wells', regionCode: 'gb-eng-ken' },
  { city: 'Royal Tunbridge Wells', regionCode: 'gb-eng-ken' },
  { city: 'Sevenoaks', regionCode: 'gb-eng-ken' },
  { city: 'Ashford', regionCode: 'gb-eng-ken' },
  { city: 'Dover', regionCode: 'gb-eng-ken' },
  { city: 'Folkestone', regionCode: 'gb-eng-ken' },
  { city: 'Dartford', regionCode: 'gb-eng-ken' },
  { city: 'Gravesend', regionCode: 'gb-eng-ken' },
  { city: 'Sittingbourne', regionCode: 'gb-eng-ken' },
  { city: 'Margate', regionCode: 'gb-eng-ken' },
  { city: 'Ramsgate', regionCode: 'gb-eng-ken' },
  { city: 'Whitstable', regionCode: 'gb-eng-ken' },
  { city: 'Tonbridge', regionCode: 'gb-eng-ken' },
  // ── England: Lancashire ───────────────────────────────────────────────────
  { city: 'Lancaster', regionCode: 'gb-eng-lan' },
  { city: 'Preston', regionCode: 'gb-eng-lan' },
  { city: 'Burnley', regionCode: 'gb-eng-lan' },
  { city: 'Accrington', regionCode: 'gb-eng-lan' },
  { city: 'Chorley', regionCode: 'gb-eng-lan' },
  { city: 'Ormskirk', regionCode: 'gb-eng-lan' },
  { city: 'Morecambe', regionCode: 'gb-eng-lan' },
  // ── England: Leicestershire ───────────────────────────────────────────────
  { city: 'Loughborough', regionCode: 'gb-eng-lec' },
  { city: 'Melton Mowbray', regionCode: 'gb-eng-lec' },
  { city: 'Hinckley', regionCode: 'gb-eng-lec' },
  { city: 'Market Harborough', regionCode: 'gb-eng-lec' },
  // ── England: Lincolnshire ─────────────────────────────────────────────────
  { city: 'Lincoln', regionCode: 'gb-eng-lin' },
  { city: 'Grantham', regionCode: 'gb-eng-lin' },
  { city: 'Skegness', regionCode: 'gb-eng-lin' },
  { city: 'Stamford', regionCode: 'gb-eng-lin' },
  { city: 'Boston', regionCode: 'gb-eng-lin' },
  { city: 'Spalding', regionCode: 'gb-eng-lin' },
  // ── England: Norfolk ──────────────────────────────────────────────────────
  { city: 'Norwich', regionCode: 'gb-eng-nfk' },
  { city: 'Great Yarmouth', regionCode: 'gb-eng-nfk' },
  { city: "King's Lynn", regionCode: 'gb-eng-nfk' },
  { city: 'Thetford', regionCode: 'gb-eng-nfk' },
  { city: 'Dereham', regionCode: 'gb-eng-nfk' },
  { city: 'Fakenham', regionCode: 'gb-eng-nfk' },
  // ── England: North Yorkshire ──────────────────────────────────────────────
  { city: 'Harrogate', regionCode: 'gb-eng-nyk' },
  { city: 'Northallerton', regionCode: 'gb-eng-nyk' },
  { city: 'Scarborough', regionCode: 'gb-eng-nyk' },
  { city: 'Ripon', regionCode: 'gb-eng-nyk' },
  { city: 'Skipton', regionCode: 'gb-eng-nyk' },
  { city: 'Whitby', regionCode: 'gb-eng-nyk' },
  { city: 'Thirsk', regionCode: 'gb-eng-nyk' },
  // ── England: Nottinghamshire ──────────────────────────────────────────────
  { city: 'Mansfield', regionCode: 'gb-eng-ntt' },
  { city: 'Newark', regionCode: 'gb-eng-ntt' },
  { city: 'Worksop', regionCode: 'gb-eng-ntt' },
  { city: 'Retford', regionCode: 'gb-eng-ntt' },
  { city: 'Newark-on-Trent', regionCode: 'gb-eng-ntt' },
  // ── England: Oxfordshire ──────────────────────────────────────────────────
  { city: 'Oxford', regionCode: 'gb-eng-oxf' },
  { city: 'Banbury', regionCode: 'gb-eng-oxf' },
  { city: 'Abingdon', regionCode: 'gb-eng-oxf' },
  { city: 'Bicester', regionCode: 'gb-eng-oxf' },
  { city: 'Witney', regionCode: 'gb-eng-oxf' },
  // ── England: Somerset ─────────────────────────────────────────────────────
  { city: 'Taunton', regionCode: 'gb-eng-som' },
  { city: 'Wells', regionCode: 'gb-eng-som' },
  { city: 'Yeovil', regionCode: 'gb-eng-som' },
  { city: 'Bridgwater', regionCode: 'gb-eng-som' },
  { city: 'Frome', regionCode: 'gb-eng-som' },
  { city: 'Glastonbury', regionCode: 'gb-eng-som' },
  // ── England: Staffordshire ────────────────────────────────────────────────
  { city: 'Stafford', regionCode: 'gb-eng-sts' },
  { city: 'Lichfield', regionCode: 'gb-eng-sts' },
  { city: 'Tamworth', regionCode: 'gb-eng-sts' },
  { city: 'Cannock', regionCode: 'gb-eng-sts' },
  { city: 'Burton upon Trent', regionCode: 'gb-eng-sts' },
  { city: 'Newcastle-under-Lyme', regionCode: 'gb-eng-sts' },
  // ── England: Suffolk ──────────────────────────────────────────────────────
  { city: 'Ipswich', regionCode: 'gb-eng-sfk' },
  { city: 'Bury St Edmunds', regionCode: 'gb-eng-sfk' },
  { city: 'Lowestoft', regionCode: 'gb-eng-sfk' },
  { city: 'Felixstowe', regionCode: 'gb-eng-sfk' },
  { city: 'Sudbury', regionCode: 'gb-eng-sfk' },
  // ── England: Surrey ───────────────────────────────────────────────────────
  { city: 'Guildford', regionCode: 'gb-eng-sry' },
  { city: 'Woking', regionCode: 'gb-eng-sry' },
  { city: 'Reigate', regionCode: 'gb-eng-sry' },
  { city: 'Epsom', regionCode: 'gb-eng-sry' },
  { city: 'Redhill', regionCode: 'gb-eng-sry' },
  { city: 'Leatherhead', regionCode: 'gb-eng-sry' },
  { city: 'Farnham', regionCode: 'gb-eng-sry' },
  { city: 'Camberley', regionCode: 'gb-eng-sry' },
  // ── England: Warwickshire ─────────────────────────────────────────────────
  { city: 'Warwick', regionCode: 'gb-eng-war' },
  { city: 'Leamington Spa', regionCode: 'gb-eng-war' },
  { city: 'Royal Leamington Spa', regionCode: 'gb-eng-war' },
  { city: 'Nuneaton', regionCode: 'gb-eng-war' },
  { city: 'Stratford-upon-Avon', regionCode: 'gb-eng-war' },
  { city: 'Rugby', regionCode: 'gb-eng-war' },
  // ── England: West Sussex ──────────────────────────────────────────────────
  { city: 'Crawley', regionCode: 'gb-eng-wsx' },
  { city: 'Worthing', regionCode: 'gb-eng-wsx' },
  { city: 'Chichester', regionCode: 'gb-eng-wsx' },
  { city: 'Bognor Regis', regionCode: 'gb-eng-wsx' },
  { city: 'Horsham', regionCode: 'gb-eng-wsx' },
  { city: 'Burgess Hill', regionCode: 'gb-eng-wsx' },
  // ── England: Worcestershire ───────────────────────────────────────────────
  { city: 'Worcester', regionCode: 'gb-eng-wor' },
  { city: 'Kidderminster', regionCode: 'gb-eng-wor' },
  { city: 'Redditch', regionCode: 'gb-eng-wor' },
  { city: 'Evesham', regionCode: 'gb-eng-wor' },
  { city: 'Malvern', regionCode: 'gb-eng-wor' },
  // ── England: London boroughs ───────────────────────────────────────────────
  { city: 'London', regionCode: 'gb-eng-lnd' },
  { city: 'City of London', regionCode: 'gb-eng-lnd' },
  { city: 'Barking', regionCode: 'gb-eng-bdg' },
  { city: 'Dagenham', regionCode: 'gb-eng-bdg' },
  { city: 'Wembley', regionCode: 'gb-eng-ben' },
  { city: 'Bromley', regionCode: 'gb-eng-bry' },
  { city: 'Camden', regionCode: 'gb-eng-cmd' },
  { city: 'Croydon', regionCode: 'gb-eng-cry' },
  { city: 'Ealing', regionCode: 'gb-eng-eal' },
  { city: 'Enfield', regionCode: 'gb-eng-enf' },
  { city: 'Greenwich', regionCode: 'gb-eng-gre' },
  { city: 'Woolwich', regionCode: 'gb-eng-gre' },
  { city: 'Hackney', regionCode: 'gb-eng-hck' },
  { city: 'Hammersmith', regionCode: 'gb-eng-hmf' },
  { city: 'Fulham', regionCode: 'gb-eng-hmf' },
  { city: 'Haringey', regionCode: 'gb-eng-hry' },
  { city: 'Tottenham', regionCode: 'gb-eng-hry' },
  { city: 'Harrow', regionCode: 'gb-eng-hrw' },
  { city: 'Romford', regionCode: 'gb-eng-hav' },
  { city: 'Uxbridge', regionCode: 'gb-eng-hil' },
  { city: 'Hounslow', regionCode: 'gb-eng-hns' },
  { city: 'Islington', regionCode: 'gb-eng-isl' },
  { city: 'Kensington', regionCode: 'gb-eng-kec' },
  { city: 'Chelsea', regionCode: 'gb-eng-kec' },
  { city: 'Kingston upon Thames', regionCode: 'gb-eng-ktt' },
  { city: 'Kingston', regionCode: 'gb-eng-ktt' },
  { city: 'Lambeth', regionCode: 'gb-eng-lbh' },
  { city: 'Brixton', regionCode: 'gb-eng-lbh' },
  { city: 'Lewisham', regionCode: 'gb-eng-lew' },
  { city: 'Wimbledon', regionCode: 'gb-eng-mrt' },
  { city: 'Stratford', regionCode: 'gb-eng-nwm' },
  { city: 'Ilford', regionCode: 'gb-eng-rdb' },
  { city: 'Richmond', regionCode: 'gb-eng-ric' },
  { city: 'Twickenham', regionCode: 'gb-eng-ric' },
  { city: 'Southwark', regionCode: 'gb-eng-swk' },
  { city: 'Bermondsey', regionCode: 'gb-eng-swk' },
  { city: 'Sutton', regionCode: 'gb-eng-stn' },
  { city: 'Tower Hamlets', regionCode: 'gb-eng-twh' },
  { city: 'Bethnal Green', regionCode: 'gb-eng-twh' },
  { city: 'Poplar', regionCode: 'gb-eng-twh' },
  { city: 'Whitechapel', regionCode: 'gb-eng-twh' },
  { city: 'Chingford', regionCode: 'gb-eng-wft' },
  { city: 'Wandsworth', regionCode: 'gb-eng-wnd' },
  { city: 'Battersea', regionCode: 'gb-eng-wnd' },
  { city: 'Westminster', regionCode: 'gb-eng-wsm' },
  { city: 'Paddington', regionCode: 'gb-eng-wsm' },
  { city: 'Soho', regionCode: 'gb-eng-wsm' },
  // ── England: Metropolitan districts ───────────────────────────────────────
  { city: 'Barnsley', regionCode: 'gb-eng-bns' },
  { city: 'Birmingham', regionCode: 'gb-eng-bir' },
  { city: 'Bolton', regionCode: 'gb-eng-bol' },
  { city: 'Bradford', regionCode: 'gb-eng-brd' },
  { city: 'Halifax', regionCode: 'gb-eng-cld' },
  { city: 'Coventry', regionCode: 'gb-eng-cov' },
  { city: 'Doncaster', regionCode: 'gb-eng-dnc' },
  { city: 'Dudley', regionCode: 'gb-eng-dud' },
  { city: 'Gateshead', regionCode: 'gb-eng-gat' },
  { city: 'Huddersfield', regionCode: 'gb-eng-kir' },
  { city: 'Dewsbury', regionCode: 'gb-eng-kir' },
  { city: 'Kirkby', regionCode: 'gb-eng-kwl' },
  { city: 'Leeds', regionCode: 'gb-eng-lds' },
  { city: 'Liverpool', regionCode: 'gb-eng-liv' },
  { city: 'Manchester', regionCode: 'gb-eng-man' },
  { city: 'Newcastle', regionCode: 'gb-eng-net' },
  { city: 'Newcastle upon Tyne', regionCode: 'gb-eng-net' },
  { city: 'Whitley Bay', regionCode: 'gb-eng-nty' },
  { city: 'Oldham', regionCode: 'gb-eng-old' },
  { city: 'Rochdale', regionCode: 'gb-eng-rch' },
  { city: 'Rotherham', regionCode: 'gb-eng-rot' },
  { city: 'St Helens', regionCode: 'gb-eng-shn' },
  { city: 'Salford', regionCode: 'gb-eng-slf' },
  { city: 'West Bromwich', regionCode: 'gb-eng-saw' },
  { city: 'Bootle', regionCode: 'gb-eng-sft' },
  { city: 'Southport', regionCode: 'gb-eng-sft' },
  { city: 'Sheffield', regionCode: 'gb-eng-shf' },
  { city: 'Solihull', regionCode: 'gb-eng-sol' },
  { city: 'South Shields', regionCode: 'gb-eng-sty' },
  { city: 'Stockport', regionCode: 'gb-eng-skp' },
  { city: 'Sunderland', regionCode: 'gb-eng-snd' },
  { city: 'Ashton-under-Lyne', regionCode: 'gb-eng-tam' },
  { city: 'Wakefield', regionCode: 'gb-eng-wkf' },
  { city: 'Walsall', regionCode: 'gb-eng-wll' },
  { city: 'Wigan', regionCode: 'gb-eng-wgn' },
  { city: 'Birkenhead', regionCode: 'gb-eng-wrl' },
  { city: 'Wolverhampton', regionCode: 'gb-eng-wlv' },
  // ── England: Unitary authorities ──────────────────────────────────────────
  { city: 'Bath', regionCode: 'gb-eng-bas' },
  { city: 'Bedford', regionCode: 'gb-eng-bdf' },
  { city: 'Blackburn', regionCode: 'gb-eng-bbd' },
  { city: 'Darwen', regionCode: 'gb-eng-bbd' },
  { city: 'Blackpool', regionCode: 'gb-eng-bpl' },
  { city: 'Bournemouth', regionCode: 'gb-eng-bcp' },
  { city: 'Christchurch', regionCode: 'gb-eng-bcp' },
  { city: 'Poole', regionCode: 'gb-eng-bcp' },
  { city: 'Bracknell', regionCode: 'gb-eng-brc' },
  { city: 'Brighton', regionCode: 'gb-eng-bnh' },
  { city: 'Hove', regionCode: 'gb-eng-bnh' },
  { city: 'Bristol', regionCode: 'gb-eng-bst' },
  { city: 'Aylesbury', regionCode: 'gb-eng-bkm' },
  { city: 'High Wycombe', regionCode: 'gb-eng-bkm' },
  { city: 'Chesham', regionCode: 'gb-eng-bkm' },
  { city: 'Amersham', regionCode: 'gb-eng-bkm' },
  { city: 'Sandy', regionCode: 'gb-eng-cbf' },
  { city: 'Biggleswade', regionCode: 'gb-eng-cbf' },
  { city: 'Macclesfield', regionCode: 'gb-eng-che' },
  { city: 'Crewe', regionCode: 'gb-eng-che' },
  { city: 'Sandbach', regionCode: 'gb-eng-che' },
  { city: 'Chester', regionCode: 'gb-eng-chw' },
  { city: 'Ellesmere Port', regionCode: 'gb-eng-chw' },
  { city: 'Northwich', regionCode: 'gb-eng-chw' },
  { city: 'Truro', regionCode: 'gb-eng-con' },
  { city: 'Penzance', regionCode: 'gb-eng-con' },
  { city: 'Newquay', regionCode: 'gb-eng-con' },
  { city: 'Falmouth', regionCode: 'gb-eng-con' },
  { city: 'St Austell', regionCode: 'gb-eng-con' },
  { city: 'Bodmin', regionCode: 'gb-eng-con' },
  { city: 'Darlington', regionCode: 'gb-eng-dal' },
  { city: 'Derby', regionCode: 'gb-eng-der' },
  { city: 'Durham', regionCode: 'gb-eng-dur' },
  { city: 'Durham City', regionCode: 'gb-eng-dur' },
  { city: 'Beverley', regionCode: 'gb-eng-ery' },
  { city: 'Bridlington', regionCode: 'gb-eng-ery' },
  { city: 'Driffield', regionCode: 'gb-eng-ery' },
  { city: 'Runcorn', regionCode: 'gb-eng-hal' },
  { city: 'Widnes', regionCode: 'gb-eng-hal' },
  { city: 'Hartlepool', regionCode: 'gb-eng-hpl' },
  { city: 'Hereford', regionCode: 'gb-eng-hef' },
  { city: 'Newport (Isle of Wight)', regionCode: 'gb-eng-iow' },
  { city: 'Ryde', regionCode: 'gb-eng-iow' },
  { city: 'Cowes', regionCode: 'gb-eng-iow' },
  { city: 'Sandown', regionCode: 'gb-eng-iow' },
  { city: 'St Marys', regionCode: 'gb-eng-ios' },
  { city: 'Hull', regionCode: 'gb-eng-khl' },
  { city: 'Kingston upon Hull', regionCode: 'gb-eng-khl' },
  { city: 'Leicester', regionCode: 'gb-eng-lce' },
  { city: 'Luton', regionCode: 'gb-eng-lut' },
  { city: 'Rochester', regionCode: 'gb-eng-mdw' },
  { city: 'Chatham', regionCode: 'gb-eng-mdw' },
  { city: 'Gillingham', regionCode: 'gb-eng-mdw' },
  { city: 'Middlesbrough', regionCode: 'gb-eng-mdb' },
  { city: 'Milton Keynes', regionCode: 'gb-eng-mik' },
  { city: 'Grimsby', regionCode: 'gb-eng-nel' },
  { city: 'Cleethorpes', regionCode: 'gb-eng-nel' },
  { city: 'Scunthorpe', regionCode: 'gb-eng-nln' },
  { city: 'Kettering', regionCode: 'gb-eng-nnh' },
  { city: 'Corby', regionCode: 'gb-eng-nnh' },
  { city: 'Wellingborough', regionCode: 'gb-eng-nnh' },
  { city: 'Weston-super-Mare', regionCode: 'gb-eng-nsm' },
  { city: 'Clevedon', regionCode: 'gb-eng-nsm' },
  { city: 'Hexham', regionCode: 'gb-eng-nbl' },
  { city: 'Berwick-upon-Tweed', regionCode: 'gb-eng-nbl' },
  { city: 'Ashington', regionCode: 'gb-eng-nbl' },
  { city: 'Blyth', regionCode: 'gb-eng-nbl' },
  { city: 'Nottingham', regionCode: 'gb-eng-ngm' },
  { city: 'Peterborough', regionCode: 'gb-eng-pte' },
  { city: 'Plymouth', regionCode: 'gb-eng-ply' },
  { city: 'Portsmouth', regionCode: 'gb-eng-por' },
  { city: 'Reading', regionCode: 'gb-eng-rdg' },
  { city: 'Redcar', regionCode: 'gb-eng-rcc' },
  { city: 'Oakham', regionCode: 'gb-eng-rut' },
  { city: 'Uppingham', regionCode: 'gb-eng-rut' },
  { city: 'Shrewsbury', regionCode: 'gb-eng-shr' },
  { city: 'Oswestry', regionCode: 'gb-eng-shr' },
  { city: 'Ludlow', regionCode: 'gb-eng-shr' },
  { city: 'Slough', regionCode: 'gb-eng-slg' },
  { city: 'Thornbury', regionCode: 'gb-eng-sgc' },
  { city: 'Yate', regionCode: 'gb-eng-sgc' },
  { city: 'Southampton', regionCode: 'gb-eng-sth' },
  { city: 'Southend-on-Sea', regionCode: 'gb-eng-sos' },
  { city: 'Southend', regionCode: 'gb-eng-sos' },
  { city: 'Stockton-on-Tees', regionCode: 'gb-eng-stt' },
  { city: 'Stockton', regionCode: 'gb-eng-stt' },
  { city: 'Stoke-on-Trent', regionCode: 'gb-eng-ste' },
  { city: 'Stoke', regionCode: 'gb-eng-ste' },
  { city: 'Hanley', regionCode: 'gb-eng-ste' },
  { city: 'Swindon', regionCode: 'gb-eng-swd' },
  { city: 'Telford', regionCode: 'gb-eng-tfw' },
  { city: 'Grays', regionCode: 'gb-eng-thr' },
  { city: 'Tilbury', regionCode: 'gb-eng-thr' },
  { city: 'Torquay', regionCode: 'gb-eng-tob' },
  { city: 'Paignton', regionCode: 'gb-eng-tob' },
  { city: 'Brixham', regionCode: 'gb-eng-tob' },
  { city: 'Warrington', regionCode: 'gb-eng-wrt' },
  { city: 'Newbury', regionCode: 'gb-eng-wbk' },
  { city: 'Thatcham', regionCode: 'gb-eng-wbk' },
  { city: 'Northampton', regionCode: 'gb-eng-wnh' },
  { city: 'Daventry', regionCode: 'gb-eng-wnh' },
  { city: 'Towcester', regionCode: 'gb-eng-wnh' },
  { city: 'Salisbury', regionCode: 'gb-eng-wil' },
  { city: 'Chippenham', regionCode: 'gb-eng-wil' },
  { city: 'Trowbridge', regionCode: 'gb-eng-wil' },
  { city: 'Windsor', regionCode: 'gb-eng-wnm' },
  { city: 'Maidenhead', regionCode: 'gb-eng-wnm' },
  { city: 'Wokingham', regionCode: 'gb-eng-wok' },
  { city: 'York', regionCode: 'gb-eng-yor' },
  // ── Scotland ──────────────────────────────────────────────────────────────
  // ── Scotland — cities map to community short codes ─────────────────────────
  { city: 'Edinburgh', regionCode: 'edi' },
  { city: 'Musselburgh', regionCode: 'edi' },
  { city: 'Dalkeith', regionCode: 'edi' },
  { city: 'Penicuik', regionCode: 'edi' },
  { city: 'Bonnyrigg', regionCode: 'edi' },
  { city: 'Haddington', regionCode: 'edi' },
  { city: 'North Berwick', regionCode: 'edi' },
  { city: 'Glasgow', regionCode: 'gla' },
  { city: 'Paisley', regionCode: 'gla' },
  { city: 'Greenock', regionCode: 'gla' },
  { city: 'Port Glasgow', regionCode: 'gla' },
  { city: 'Coatbridge', regionCode: 'gla' },
  { city: 'Airdrie', regionCode: 'gla' },
  { city: 'Motherwell', regionCode: 'gla' },
  { city: 'Hamilton', regionCode: 'gla' },
  { city: 'East Kilbride', regionCode: 'gla' },
  { city: 'Bearsden', regionCode: 'gla' },
  { city: 'Clydebank', regionCode: 'gla' },
  { city: 'Dumbarton', regionCode: 'gla' },
  { city: 'Renfrew', regionCode: 'gla' },
  { city: 'Barrhead', regionCode: 'gla' },
  { city: 'Newton Mearns', regionCode: 'gla' },
  { city: 'Falkirk', regionCode: 'fal' },
  { city: 'Grangemouth', regionCode: 'fal' },
  { city: "Bo'ness", regionCode: 'fal' },
  { city: 'Dundee', regionCode: 'dun' },
  { city: 'Arbroath', regionCode: 'dun' },
  { city: 'Montrose', regionCode: 'dun' },
  { city: 'Perth', regionCode: 'per' },
  { city: 'Kinross', regionCode: 'per' },
  { city: 'Pitlochry', regionCode: 'per' },
  { city: 'Blairgowrie', regionCode: 'per' },
  { city: 'Kirkcaldy', regionCode: 'fif' },
  { city: 'Dunfermline', regionCode: 'fif' },
  { city: 'Glenrothes', regionCode: 'fif' },
  { city: 'St Andrews', regionCode: 'fif' },
  { city: 'Alloa', regionCode: 'cen' },
  { city: 'Stirling', regionCode: 'cen' },
  { city: 'Bridge of Allan', regionCode: 'cen' },
  { city: 'Livingston', regionCode: 'cen' },
  { city: 'Bathgate', regionCode: 'cen' },
  { city: 'Kirkintilloch', regionCode: 'cen' },
  { city: 'Cumbernauld', regionCode: 'cen' },
  // Tayside area (Dundee/Perth/Angus corridor)
  { city: 'Forfar', regionCode: 'tay' },
  { city: 'Kirriemuir', regionCode: 'tay' },
  // Areas without a specific code fall back to sco
  { city: 'Aberdeen', regionCode: 'sco' },
  { city: 'Inverness', regionCode: 'sco' },
  { city: 'Elgin', regionCode: 'sco' },
  { city: 'Fort William', regionCode: 'sco' },
  { city: 'Aviemore', regionCode: 'sco' },
  { city: 'Wick', regionCode: 'sco' },
  { city: 'Thurso', regionCode: 'sco' },
  { city: 'Ayr', regionCode: 'gla' },
  { city: 'Kilmarnock', regionCode: 'gla' },
  { city: 'Irvine', regionCode: 'gla' },
  { city: 'Dumfries', regionCode: 'sco' },
  { city: 'Galashiels', regionCode: 'sco' },
  { city: 'Hawick', regionCode: 'sco' },
  { city: 'Stornoway', regionCode: 'sco' },
  { city: 'Kirkwall', regionCode: 'sco' },
  { city: 'Lerwick', regionCode: 'sco' },
  // ── Wales ─────────────────────────────────────────────────────────────────
  { city: 'Ebbw Vale', regionCode: 'gb-wls-bgw' },
  { city: 'Abertillery', regionCode: 'gb-wls-bgw' },
  { city: 'Tredegar', regionCode: 'gb-wls-bgw' },
  { city: 'Bridgend', regionCode: 'gb-wls-bge' },
  { city: 'Porthcawl', regionCode: 'gb-wls-bge' },
  { city: 'Maesteg', regionCode: 'gb-wls-bge' },
  { city: 'Caerphilly', regionCode: 'gb-wls-cay' },
  { city: 'Bargoed', regionCode: 'gb-wls-cay' },
  { city: 'Blackwood', regionCode: 'gb-wls-cay' },
  { city: 'Cardiff', regionCode: 'gb-wls-crf' },
  { city: 'Carmarthen', regionCode: 'gb-wls-cmn' },
  { city: 'Llanelli', regionCode: 'gb-wls-cmn' },
  { city: 'Ammanford', regionCode: 'gb-wls-cmn' },
  { city: 'Aberystwyth', regionCode: 'gb-wls-cgn' },
  { city: 'Cardigan', regionCode: 'gb-wls-cgn' },
  { city: 'Lampeter', regionCode: 'gb-wls-cgn' },
  { city: 'Llandudno', regionCode: 'gb-wls-cwy' },
  { city: 'Colwyn Bay', regionCode: 'gb-wls-cwy' },
  { city: 'Conwy', regionCode: 'gb-wls-cwy' },
  { city: 'Rhyl', regionCode: 'gb-wls-den' },
  { city: 'Denbigh', regionCode: 'gb-wls-den' },
  { city: 'Ruthin', regionCode: 'gb-wls-den' },
  { city: 'Llangollen', regionCode: 'gb-wls-den' },
  { city: 'Flint', regionCode: 'gb-wls-fln' },
  { city: 'Mold', regionCode: 'gb-wls-fln' },
  { city: 'Holywell', regionCode: 'gb-wls-fln' },
  { city: 'Bangor', regionCode: 'gb-wls-gwn' },
  { city: 'Caernarfon', regionCode: 'gb-wls-gwn' },
  { city: 'Pwllheli', regionCode: 'gb-wls-gwn' },
  { city: 'Porthmadog', regionCode: 'gb-wls-gwn' },
  { city: 'Holyhead', regionCode: 'gb-wls-agy' },
  { city: 'Llangefni', regionCode: 'gb-wls-agy' },
  { city: 'Amlwch', regionCode: 'gb-wls-agy' },
  { city: 'Merthyr Tydfil', regionCode: 'gb-wls-mty' },
  { city: 'Abergavenny', regionCode: 'gb-wls-mon' },
  { city: 'Monmouth', regionCode: 'gb-wls-mon' },
  { city: 'Caldicot', regionCode: 'gb-wls-mon' },
  { city: 'Neath', regionCode: 'gb-wls-ntl' },
  { city: 'Port Talbot', regionCode: 'gb-wls-ntl' },
  { city: 'Aberavon', regionCode: 'gb-wls-ntl' },
  { city: 'Newport', regionCode: 'gb-wls-nwp' },
  { city: 'Haverfordwest', regionCode: 'gb-wls-pem' },
  { city: 'Pembroke', regionCode: 'gb-wls-pem' },
  { city: 'Milford Haven', regionCode: 'gb-wls-pem' },
  { city: 'Fishguard', regionCode: 'gb-wls-pem' },
  { city: 'Newtown', regionCode: 'gb-wls-pow' },
  { city: 'Welshpool', regionCode: 'gb-wls-pow' },
  { city: 'Brecon', regionCode: 'gb-wls-pow' },
  { city: 'Llandrindod Wells', regionCode: 'gb-wls-pow' },
  { city: 'Machynlleth', regionCode: 'gb-wls-pow' },
  { city: 'Pontypridd', regionCode: 'gb-wls-rct' },
  { city: 'Rhondda', regionCode: 'gb-wls-rct' },
  { city: 'Aberdare', regionCode: 'gb-wls-rct' },
  { city: 'Mountain Ash', regionCode: 'gb-wls-rct' },
  { city: 'Swansea', regionCode: 'gb-wls-swa' },
  { city: 'Mumbles', regionCode: 'gb-wls-swa' },
  { city: 'Pontypool', regionCode: 'gb-wls-tof' },
  { city: 'Cwmbran', regionCode: 'gb-wls-tof' },
  { city: 'Barry', regionCode: 'gb-wls-vgl' },
  { city: 'Penarth', regionCode: 'gb-wls-vgl' },
  { city: 'Cowbridge', regionCode: 'gb-wls-vgl' },
  { city: 'Wrexham', regionCode: 'gb-wls-wrx' },
  // ── Northern Ireland ──────────────────────────────────────────────────────
  // ── Northern Ireland — all cities map to ioi ───────────────────────────────
  { city: 'Belfast', regionCode: 'ioi' },
  { city: 'Derry', regionCode: 'ioi' },
  { city: 'Londonderry', regionCode: 'ioi' },
  { city: 'Antrim', regionCode: 'ioi' },
  { city: 'Armagh', regionCode: 'ioi' },
  { city: 'Bangor (NI)', regionCode: 'ioi' },
  { city: 'Lisburn', regionCode: 'ioi' },
  { city: 'Newry', regionCode: 'ioi' },
  { city: 'Newtownabbey', regionCode: 'ioi' },
  { city: 'Omagh', regionCode: 'ioi' },
  { city: 'Enniskillen', regionCode: 'ioi' },
  { city: 'Ballymena', regionCode: 'ioi' },
  { city: 'Coleraine', regionCode: 'ioi' },
  { city: 'Downpatrick', regionCode: 'ioi' },
  { city: 'Strabane', regionCode: 'ioi' },
];

export const COUNTRY_LABELS: Record<string, string> = {
  'gb-eng': 'England',
  'gb-sct': 'Scotland',
  'gb-wls': 'Wales',
  'gb-nir': 'Northern Ireland',
};

// ── Relationships ─────────────────────────────────────────────────────────────

// Constituent country top-level codes for England and Wales only.
// Scotland and NI use their own short codes and appear directly in REGIONS.
export const CONSTITUENT_COUNTRIES: Region[] = [
  { code: 'gb-eng', name: 'England', countryCode: 'gb-eng' },
  { code: 'gb-wls', name: 'Wales',   countryCode: 'gb-wls' },
];

export type RegionRelationships = {
  historicParent?: string; // code of the historic county this was carved from
  group?: string;          // name of the modern geographic grouping
  networkCode?: string;    // current MeshCore network code used instead of the region scope
};

// Modern geographic groupings (post-1974 metropolitan counties and equivalents)
export const GEOGRAPHIC_GROUPS: Record<string, string[]> = {
  'Greater London': [
    'gb-eng-lnd', 'gb-eng-bdg', 'gb-eng-bne', 'gb-eng-bex', 'gb-eng-ben',
    'gb-eng-bry', 'gb-eng-cmd', 'gb-eng-cry', 'gb-eng-eal', 'gb-eng-enf',
    'gb-eng-gre', 'gb-eng-hck', 'gb-eng-hmf', 'gb-eng-hry', 'gb-eng-hrw',
    'gb-eng-hav', 'gb-eng-hil', 'gb-eng-hns', 'gb-eng-isl', 'gb-eng-kec',
    'gb-eng-ktt', 'gb-eng-lbh', 'gb-eng-lew', 'gb-eng-mrt', 'gb-eng-nwm',
    'gb-eng-rdb', 'gb-eng-ric', 'gb-eng-swk', 'gb-eng-stn', 'gb-eng-twh',
    'gb-eng-wft', 'gb-eng-wnd', 'gb-eng-wsm',
  ],
  'Greater Manchester': [
    'gb-eng-man', 'gb-eng-slf', 'gb-eng-old', 'gb-eng-rch', 'gb-eng-bur',
    'gb-eng-tam', 'gb-eng-skp', 'gb-eng-trf', 'gb-eng-wgn', 'gb-eng-bol',
  ],
  'West Midlands': [
    'gb-eng-bir', 'gb-eng-cov', 'gb-eng-wlv', 'gb-eng-wll',
    'gb-eng-dud', 'gb-eng-saw', 'gb-eng-sol',
  ],
  'Merseyside': [
    'gb-eng-liv', 'gb-eng-kwl', 'gb-eng-sft', 'gb-eng-shn', 'gb-eng-wrl',
  ],
  'West Yorkshire': [
    'gb-eng-brd', 'gb-eng-lds', 'gb-eng-cld', 'gb-eng-kir', 'gb-eng-wkf',
  ],
  'South Yorkshire': [
    'gb-eng-shf', 'gb-eng-rot', 'gb-eng-dnc', 'gb-eng-bns',
  ],
  'Tyne and Wear': [
    'gb-eng-net', 'gb-eng-nty', 'gb-eng-gat', 'gb-eng-snd', 'gb-eng-sty',
  ],
};

// Relationships between regions and their historic counties / geographic groups.
// London boroughs not listed under a historicParent were historically in Middlesex
// (which no longer exists as an administrative unit in the spec).
// Parent of each Scottish short code in the region tree (* = root = null).
// 'sco' and 'ioi' are children of *, the others are children of 'sco'.
export const SCOTLAND_PARENTS: Record<string, string | null> = {
  sco: null,
  ioi: null,
  cen: 'sco', fif: 'sco', tay: 'sco', gla: 'sco',
  edi: 'sco', fal: 'sco', dun: 'sco', per: 'sco',
};

export const REGION_RELATIONSHIPS: Record<string, RegionRelationships> = {
  // Greater London — historic county relationships
  'gb-eng-lnd': { group: 'Greater London' },
  'gb-eng-bdg': { historicParent: 'gb-eng-ess', group: 'Greater London' },
  'gb-eng-bne': { historicParent: 'gb-eng-hrt', group: 'Greater London' },
  'gb-eng-bex': { historicParent: 'gb-eng-ken', group: 'Greater London' },
  'gb-eng-ben': { group: 'Greater London' },
  'gb-eng-bry': { historicParent: 'gb-eng-ken', group: 'Greater London' },
  'gb-eng-cmd': { group: 'Greater London' },
  'gb-eng-cry': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-eal': { group: 'Greater London' },
  'gb-eng-enf': { historicParent: 'gb-eng-hrt', group: 'Greater London' },
  'gb-eng-gre': { historicParent: 'gb-eng-ken', group: 'Greater London' },
  'gb-eng-hck': { group: 'Greater London' },
  'gb-eng-hmf': { group: 'Greater London' },
  'gb-eng-hry': { group: 'Greater London' },
  'gb-eng-hrw': { group: 'Greater London' },
  'gb-eng-hav': { historicParent: 'gb-eng-ess', group: 'Greater London' },
  'gb-eng-hil': { group: 'Greater London' },
  'gb-eng-hns': { group: 'Greater London' },
  'gb-eng-isl': { group: 'Greater London' },
  'gb-eng-kec': { group: 'Greater London' },
  'gb-eng-ktt': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-lbh': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-lew': { historicParent: 'gb-eng-ken', group: 'Greater London' },
  'gb-eng-mrt': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-nwm': { historicParent: 'gb-eng-ess', group: 'Greater London' },
  'gb-eng-rdb': { historicParent: 'gb-eng-ess', group: 'Greater London' },
  'gb-eng-ric': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-swk': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-stn': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-twh': { group: 'Greater London' },
  'gb-eng-wft': { historicParent: 'gb-eng-ess', group: 'Greater London' },
  'gb-eng-wnd': { historicParent: 'gb-eng-sry', group: 'Greater London' },
  'gb-eng-wsm': { group: 'Greater London' },
  // Greater Manchester
  'gb-eng-man': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-slf': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-old': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-rch': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-bur': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-tam': { group: 'Greater Manchester' },
  'gb-eng-skp': { historicParent: 'gb-eng-che', group: 'Greater Manchester' },
  'gb-eng-trf': { historicParent: 'gb-eng-che', group: 'Greater Manchester' },
  'gb-eng-wgn': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  'gb-eng-bol': { historicParent: 'gb-eng-lan', group: 'Greater Manchester' },
  // West Midlands
  'gb-eng-bir': { historicParent: 'gb-eng-war', group: 'West Midlands' },
  'gb-eng-cov': { historicParent: 'gb-eng-war', group: 'West Midlands' },
  'gb-eng-wlv': { historicParent: 'gb-eng-sts', group: 'West Midlands' },
  'gb-eng-wll': { historicParent: 'gb-eng-sts', group: 'West Midlands' },
  'gb-eng-dud': { historicParent: 'gb-eng-wor', group: 'West Midlands' },
  'gb-eng-saw': { historicParent: 'gb-eng-sts', group: 'West Midlands' },
  'gb-eng-sol': { historicParent: 'gb-eng-war', group: 'West Midlands' },
  // Merseyside
  'gb-eng-liv': { historicParent: 'gb-eng-lan', group: 'Merseyside' },
  'gb-eng-kwl': { historicParent: 'gb-eng-lan', group: 'Merseyside' },
  'gb-eng-sft': { historicParent: 'gb-eng-lan', group: 'Merseyside' },
  'gb-eng-shn': { historicParent: 'gb-eng-lan', group: 'Merseyside' },
  'gb-eng-wrl': { historicParent: 'gb-eng-che', group: 'Merseyside' },
  // West Yorkshire
  'gb-eng-brd': { group: 'West Yorkshire' },
  'gb-eng-lds': { group: 'West Yorkshire' },
  'gb-eng-cld': { group: 'West Yorkshire' },
  'gb-eng-kir': { group: 'West Yorkshire' },
  'gb-eng-wkf': { group: 'West Yorkshire' },
  // South Yorkshire
  'gb-eng-shf': { group: 'South Yorkshire' },
  'gb-eng-rot': { group: 'South Yorkshire' },
  'gb-eng-dnc': { group: 'South Yorkshire' },
  'gb-eng-bns': { group: 'South Yorkshire' },
  // Tyne and Wear
  'gb-eng-net': { historicParent: 'gb-eng-nbl', group: 'Tyne and Wear' },
  'gb-eng-nty': { historicParent: 'gb-eng-nbl', group: 'Tyne and Wear' },
  'gb-eng-gat': { historicParent: 'gb-eng-dur', group: 'Tyne and Wear' },
  'gb-eng-snd': { historicParent: 'gb-eng-dur', group: 'Tyne and Wear' },
  'gb-eng-sty': { historicParent: 'gb-eng-dur', group: 'Tyne and Wear' },
  // Unitary authorities carved from counties
  'gb-eng-bas': { historicParent: 'gb-eng-som' },
  'gb-eng-bbd': { historicParent: 'gb-eng-lan' },
  'gb-eng-bcp': { historicParent: 'gb-eng-dor' },
  'gb-eng-bnh': { historicParent: 'gb-eng-esx' },
  'gb-eng-bst': { historicParent: 'gb-eng-gls' },
  'gb-eng-dal': { historicParent: 'gb-eng-dur' },
  'gb-eng-der': { historicParent: 'gb-eng-dby' },
  'gb-eng-hal': { historicParent: 'gb-eng-lan' },
  'gb-eng-hpl': { historicParent: 'gb-eng-dur' },
  'gb-eng-khl': { historicParent: 'gb-eng-ery' },
  'gb-eng-lce': { historicParent: 'gb-eng-lec' },
  'gb-eng-mdw': { historicParent: 'gb-eng-ken' },
  'gb-eng-mdb': { historicParent: 'gb-eng-nyk' },
  'gb-eng-mik': { historicParent: 'gb-eng-bkm' },
  'gb-eng-nel': { historicParent: 'gb-eng-lin' },
  'gb-eng-nln': { historicParent: 'gb-eng-lin' },
  'gb-eng-nsm': { historicParent: 'gb-eng-som' },
  'gb-eng-ngm': { historicParent: 'gb-eng-ntt' },
  'gb-eng-pte': { historicParent: 'gb-eng-cam' },
  'gb-eng-ply': { historicParent: 'gb-eng-dev' },
  'gb-eng-por': { historicParent: 'gb-eng-ham' },
  'gb-eng-rcc': { historicParent: 'gb-eng-nyk' },
  'gb-eng-sgc': { historicParent: 'gb-eng-gls' },
  'gb-eng-sos': { historicParent: 'gb-eng-ess' },
  'gb-eng-sth': { historicParent: 'gb-eng-ham' },
  'gb-eng-ste': { historicParent: 'gb-eng-sts' },
  'gb-eng-stt': { historicParent: 'gb-eng-dur' },
  'gb-eng-swd': { historicParent: 'gb-eng-wil' },
  'gb-eng-tfw': { historicParent: 'gb-eng-shr' },
  'gb-eng-thr': { historicParent: 'gb-eng-ess' },
  'gb-eng-tob': { historicParent: 'gb-eng-dev' },
  'gb-eng-yor': { historicParent: 'gb-eng-nyk' },
};

// Geographic adjacency map — direct land borders (bidirectional but listed once here; getNeighbors mirrors them).
// Groups (Greater London etc.) use group membership as implicit adjacency inside getNeighbors.
export const REGION_ADJACENCY: Record<string, string[]> = {
  // ── England: Counties ────────────────────────────────────────────────────────
  'gb-eng-cam': ['gb-eng-lin', 'gb-eng-nfk', 'gb-eng-sfk', 'gb-eng-ess', 'gb-eng-hrt', 'gb-eng-cbf', 'gb-eng-bdf', 'gb-eng-nnh', 'gb-eng-pte', 'gb-eng-lut'],
  'gb-eng-cma': ['gb-eng-lan', 'gb-eng-nbl', 'gb-eng-dur'],
  'gb-eng-dby': ['gb-eng-ntt', 'gb-eng-lec', 'gb-eng-sts', 'gb-eng-shf', 'gb-eng-rot', 'gb-eng-bns', 'gb-eng-nyk', 'gb-eng-der', 'gb-eng-che'],
  'gb-eng-dev': ['gb-eng-con', 'gb-eng-som', 'gb-eng-tob', 'gb-eng-ply'],
  'gb-eng-dor': ['gb-eng-bcp', 'gb-eng-wil', 'gb-eng-som', 'gb-eng-wsx'],
  'gb-eng-esx': ['gb-eng-ken', 'gb-eng-sry', 'gb-eng-bnh', 'gb-eng-lew', 'gb-eng-bry', 'gb-eng-cry'],
  'gb-eng-ess': ['gb-eng-sfk', 'gb-eng-cam', 'gb-eng-hrt', 'gb-eng-bdg', 'gb-eng-hav', 'gb-eng-nwm', 'gb-eng-rdb', 'gb-eng-wft', 'gb-eng-thr', 'gb-eng-sos', 'gb-eng-mdw', 'gb-eng-ken'],
  'gb-eng-gls': ['gb-eng-bst', 'gb-eng-sgc', 'gb-eng-wil', 'gb-eng-oxf', 'gb-eng-war', 'gb-eng-wor', 'gb-eng-hef', 'gb-eng-nsm', 'gb-wls-mon', 'gb-wls-pow'],
  'gb-eng-ham': ['gb-eng-wil', 'gb-eng-bcp', 'gb-eng-wsx', 'gb-eng-sry', 'gb-eng-brc', 'gb-eng-por', 'gb-eng-sth', 'gb-eng-iow', 'gb-eng-wbk', 'gb-eng-wok'],
  'gb-eng-hef': ['gb-eng-gls', 'gb-eng-wor', 'gb-eng-shr', 'gb-wls-pow', 'gb-wls-mon'],
  'gb-eng-hrt': ['gb-eng-bdf', 'gb-eng-cbf', 'gb-eng-cam', 'gb-eng-ess', 'gb-eng-bdg', 'gb-eng-bne', 'gb-eng-enf', 'gb-eng-lut'],
  'gb-eng-ken': ['gb-eng-mdw', 'gb-eng-bex', 'gb-eng-gre', 'gb-eng-lew', 'gb-eng-bry', 'gb-eng-sry', 'gb-eng-esx', 'gb-eng-ess', 'gb-eng-thr'],
  'gb-eng-lan': ['gb-eng-cma', 'gb-eng-bbd', 'gb-eng-bpl', 'gb-eng-bur', 'gb-eng-rch', 'gb-eng-bol', 'gb-eng-wgn', 'gb-eng-old', 'gb-eng-man', 'gb-eng-slf', 'gb-eng-tam', 'gb-eng-skp', 'gb-eng-trf', 'gb-eng-kwl', 'gb-eng-sft', 'gb-eng-shn', 'gb-eng-liv', 'gb-eng-hal', 'gb-eng-wrt', 'gb-eng-nyk'],
  'gb-eng-lec': ['gb-eng-lce', 'gb-eng-ntt', 'gb-eng-lin', 'gb-eng-rut', 'gb-eng-nnh', 'gb-eng-war', 'gb-eng-sts', 'gb-eng-dby'],
  'gb-eng-lin': ['gb-eng-nel', 'gb-eng-nln', 'gb-eng-ntt', 'gb-eng-lec', 'gb-eng-rut', 'gb-eng-cam', 'gb-eng-nfk', 'gb-eng-ery', 'gb-eng-nyk', 'gb-eng-khl', 'gb-eng-pte'],
  'gb-eng-nfk': ['gb-eng-lin', 'gb-eng-cam', 'gb-eng-sfk'],
  'gb-eng-ntt': ['gb-eng-dby', 'gb-eng-lec', 'gb-eng-lin', 'gb-eng-rot', 'gb-eng-shf', 'gb-eng-bns', 'gb-eng-dnc', 'gb-eng-ngm', 'gb-eng-lce'],
  'gb-eng-nyk': ['gb-eng-ery', 'gb-eng-hpl', 'gb-eng-rcc', 'gb-eng-dur', 'gb-eng-mdb', 'gb-eng-stt', 'gb-eng-dal', 'gb-eng-lds', 'gb-eng-brd', 'gb-eng-wkf', 'gb-eng-bns', 'gb-eng-rot', 'gb-eng-shf', 'gb-eng-dby', 'gb-eng-lan', 'gb-eng-cma', 'gb-eng-yor', 'gb-eng-dnc'],
  'gb-eng-oxf': ['gb-eng-war', 'gb-eng-nnh', 'gb-eng-wnh', 'gb-eng-bkm', 'gb-eng-wbk', 'gb-eng-gls', 'gb-eng-mik', 'gb-eng-rdg', 'gb-eng-swd'],
  'gb-eng-sfk': ['gb-eng-nfk', 'gb-eng-cam', 'gb-eng-ess'],
  'gb-eng-som': ['gb-eng-dev', 'gb-eng-dor', 'gb-eng-wil', 'gb-eng-bas', 'gb-eng-nsm', 'gb-eng-gls'],
  'gb-eng-sry': ['gb-eng-ktt', 'gb-eng-lbh', 'gb-eng-mrt', 'gb-eng-wnd', 'gb-eng-stn', 'gb-eng-swk', 'gb-eng-cry', 'gb-eng-bry', 'gb-eng-lew', 'gb-eng-ham', 'gb-eng-wbk', 'gb-eng-wok', 'gb-eng-brc', 'gb-eng-esx', 'gb-eng-ken', 'gb-eng-bnh', 'gb-eng-wsx', 'gb-eng-ric'],
  'gb-eng-sts': ['gb-eng-dby', 'gb-eng-der', 'gb-eng-ste', 'gb-eng-lce', 'gb-eng-lec', 'gb-eng-war', 'gb-eng-wor', 'gb-eng-wlv', 'gb-eng-dud', 'gb-eng-wll', 'gb-eng-saw', 'gb-eng-bir', 'gb-eng-shr', 'gb-eng-che', 'gb-eng-chw'],
  'gb-eng-war': ['gb-eng-bir', 'gb-eng-cov', 'gb-eng-sol', 'gb-eng-sts', 'gb-eng-wor', 'gb-eng-gls', 'gb-eng-oxf', 'gb-eng-nnh', 'gb-eng-wnh', 'gb-eng-lec', 'gb-eng-dud'],
  'gb-eng-wil': ['gb-eng-gls', 'gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-ham', 'gb-eng-bcp', 'gb-eng-dor', 'gb-eng-som', 'gb-eng-bas', 'gb-eng-sgc', 'gb-eng-swd', 'gb-eng-wbk'],
  'gb-eng-wor': ['gb-eng-gls', 'gb-eng-hef', 'gb-eng-shr', 'gb-eng-sts', 'gb-eng-dud', 'gb-eng-bir', 'gb-eng-sol', 'gb-eng-war', 'gb-wls-pow'],
  'gb-eng-wsx': ['gb-eng-ham', 'gb-eng-sry', 'gb-eng-bnh', 'gb-eng-esx'],
  // ── England: Unitary authorities ─────────────────────────────────────────────
  'gb-eng-bas': ['gb-eng-bst', 'gb-eng-wil', 'gb-eng-som', 'gb-eng-nsm', 'gb-eng-sgc'],
  'gb-eng-bbd': ['gb-eng-lan', 'gb-eng-bpl'],
  'gb-eng-bcp': ['gb-eng-dor', 'gb-eng-wil', 'gb-eng-wsx'],
  'gb-eng-bdf': ['gb-eng-hrt', 'gb-eng-cbf', 'gb-eng-nnh', 'gb-eng-cam', 'gb-eng-lut'],
  'gb-eng-bkm': ['gb-eng-oxf', 'gb-eng-nnh', 'gb-eng-mik', 'gb-eng-hrt', 'gb-eng-wbk', 'gb-eng-brc', 'gb-eng-slg', 'gb-eng-wnm', 'gb-eng-wil'],
  'gb-eng-bnh': ['gb-eng-esx', 'gb-eng-wsx', 'gb-eng-sry'],
  'gb-eng-bpl': ['gb-eng-lan', 'gb-eng-bbd'],
  'gb-eng-brc': ['gb-eng-ham', 'gb-eng-sry', 'gb-eng-wok', 'gb-eng-wbk', 'gb-eng-wnm', 'gb-eng-slg'],
  'gb-eng-bst': ['gb-eng-bas', 'gb-eng-sgc', 'gb-eng-nsm', 'gb-eng-gls'],
  'gb-eng-cbf': ['gb-eng-bdf', 'gb-eng-hrt', 'gb-eng-cam', 'gb-eng-nnh', 'gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-mik', 'gb-eng-lut'],
  'gb-eng-che': ['gb-eng-skp', 'gb-eng-trf', 'gb-eng-sts', 'gb-eng-dby', 'gb-wls-fln', 'gb-wls-wrx', 'gb-eng-shr'],
  'gb-eng-chw': ['gb-eng-wrl', 'gb-eng-hal', 'gb-eng-wrt', 'gb-eng-sts', 'gb-eng-shr', 'gb-wls-fln', 'gb-wls-wrx'],
  'gb-eng-con': ['gb-eng-dev', 'gb-eng-ios'],
  'gb-eng-dal': ['gb-eng-dur', 'gb-eng-nyk', 'gb-eng-stt'],
  'gb-eng-der': ['gb-eng-dby', 'gb-eng-ste', 'gb-eng-lce', 'gb-eng-ngm'],
  'gb-eng-ery': ['gb-eng-nyk', 'gb-eng-lin', 'gb-eng-khl', 'gb-eng-yor'],
  'gb-eng-hal': ['gb-eng-wgn', 'gb-eng-shn', 'gb-eng-wrl', 'gb-eng-wrt', 'gb-eng-liv', 'gb-eng-chw'],
  'gb-eng-hpl': ['gb-eng-dur', 'gb-eng-nyk', 'gb-eng-rcc', 'gb-eng-stt', 'gb-eng-mdb'],
  'gb-eng-ios': ['gb-eng-con'],
  'gb-eng-iow': ['gb-eng-ham'],
  'gb-eng-khl': ['gb-eng-ery', 'gb-eng-lin', 'gb-eng-nel', 'gb-eng-nln'],
  'gb-eng-lce': ['gb-eng-lec', 'gb-eng-ntt', 'gb-eng-ngm', 'gb-eng-sts', 'gb-eng-der', 'gb-eng-dby'],
  'gb-eng-lut': ['gb-eng-cbf', 'gb-eng-bdf', 'gb-eng-hrt', 'gb-eng-cam'],
  'gb-eng-mdw': ['gb-eng-ken', 'gb-eng-ess', 'gb-eng-thr'],
  'gb-eng-mdb': ['gb-eng-nyk', 'gb-eng-dur', 'gb-eng-rcc', 'gb-eng-hpl', 'gb-eng-stt'],
  'gb-eng-mik': ['gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-nnh', 'gb-eng-wnh', 'gb-eng-cbf', 'gb-eng-hrt'],
  'gb-eng-nel': ['gb-eng-nln', 'gb-eng-lin', 'gb-eng-ery', 'gb-eng-khl'],
  'gb-eng-ngm': ['gb-eng-ntt', 'gb-eng-dby', 'gb-eng-lce', 'gb-eng-der'],
  'gb-eng-nln': ['gb-eng-nel', 'gb-eng-lin', 'gb-eng-ery', 'gb-eng-khl'],
  'gb-eng-nnh': ['gb-eng-lec', 'gb-eng-war', 'gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-cbf', 'gb-eng-bdf', 'gb-eng-mik', 'gb-eng-wnh'],
  'gb-eng-nsm': ['gb-eng-bst', 'gb-eng-som', 'gb-eng-sgc', 'gb-eng-bas'],
  'gb-eng-nbl': ['gb-eng-cma', 'gb-eng-dur', 'gb-eng-net', 'gb-eng-nty'],
  'gb-eng-ply': ['gb-eng-dev', 'gb-eng-con'],
  'gb-eng-por': ['gb-eng-ham'],
  'gb-eng-pte': ['gb-eng-cam', 'gb-eng-lin', 'gb-eng-nnh'],
  'gb-eng-rcc': ['gb-eng-nyk', 'gb-eng-dur', 'gb-eng-mdb', 'gb-eng-hpl', 'gb-eng-stt'],
  'gb-eng-rdg': ['gb-eng-wbk', 'gb-eng-wok', 'gb-eng-bkm', 'gb-eng-oxf', 'gb-eng-slg'],
  'gb-eng-rut': ['gb-eng-lec', 'gb-eng-lin', 'gb-eng-nnh', 'gb-eng-cam'],
  'gb-eng-sgc': ['gb-eng-bst', 'gb-eng-gls', 'gb-eng-wil', 'gb-eng-bas', 'gb-eng-nsm'],
  'gb-eng-shr': ['gb-eng-wor', 'gb-eng-hef', 'gb-eng-sts', 'gb-eng-tfw', 'gb-eng-che', 'gb-eng-chw', 'gb-wls-pow', 'gb-wls-wrx'],
  'gb-eng-slg': ['gb-eng-bkm', 'gb-eng-wnm', 'gb-eng-wok', 'gb-eng-rdg', 'gb-eng-brc'],
  'gb-eng-sos': ['gb-eng-ess', 'gb-eng-thr'],
  'gb-eng-sth': ['gb-eng-ham'],
  'gb-eng-ste': ['gb-eng-sts', 'gb-eng-che', 'gb-eng-der', 'gb-eng-dby', 'gb-eng-lce'],
  'gb-eng-stt': ['gb-eng-dur', 'gb-eng-nyk', 'gb-eng-mdb', 'gb-eng-hpl', 'gb-eng-rcc', 'gb-eng-dal'],
  'gb-eng-swd': ['gb-eng-wil', 'gb-eng-oxf', 'gb-eng-gls'],
  'gb-eng-tfw': ['gb-eng-shr', 'gb-eng-sts', 'gb-eng-wor'],
  'gb-eng-thr': ['gb-eng-ess', 'gb-eng-sos', 'gb-eng-mdw', 'gb-eng-ken'],
  'gb-eng-tob': ['gb-eng-dev'],
  'gb-eng-wbk': ['gb-eng-ham', 'gb-eng-sry', 'gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-rdg', 'gb-eng-wok', 'gb-eng-wil'],
  'gb-eng-wnh': ['gb-eng-lec', 'gb-eng-war', 'gb-eng-oxf', 'gb-eng-bkm', 'gb-eng-mik', 'gb-eng-nnh'],
  'gb-eng-wnm': ['gb-eng-bkm', 'gb-eng-brc', 'gb-eng-wok', 'gb-eng-slg'],
  'gb-eng-wok': ['gb-eng-ham', 'gb-eng-sry', 'gb-eng-brc', 'gb-eng-wnm', 'gb-eng-rdg', 'gb-eng-wbk', 'gb-eng-slg'],
  'gb-eng-wrt': ['gb-eng-chw', 'gb-eng-hal', 'gb-eng-trf', 'gb-eng-lan'],
  'gb-eng-yor': ['gb-eng-nyk', 'gb-eng-ery', 'gb-eng-lds'],
  // ── London boroughs — direct land borders ────────────────────────────────────
  // Central
  'gb-eng-lnd': ['gb-eng-isl', 'gb-eng-twh', 'gb-eng-swk', 'gb-eng-cmd'],
  'gb-eng-cmd': ['gb-eng-lnd', 'gb-eng-isl', 'gb-eng-hry', 'gb-eng-bne', 'gb-eng-kec', 'gb-eng-wsm'],
  'gb-eng-isl': ['gb-eng-lnd', 'gb-eng-cmd', 'gb-eng-hry', 'gb-eng-hck', 'gb-eng-twh'],
  'gb-eng-wsm': ['gb-eng-cmd', 'gb-eng-kec', 'gb-eng-wnd', 'gb-eng-lbh', 'gb-eng-swk'],
  'gb-eng-kec': ['gb-eng-cmd', 'gb-eng-wsm', 'gb-eng-hmf', 'gb-eng-hns', 'gb-eng-eal', 'gb-eng-ben'],
  'gb-eng-hmf': ['gb-eng-kec', 'gb-eng-hns', 'gb-eng-eal', 'gb-eng-wnd', 'gb-eng-mrt'],
  // North
  'gb-eng-bne': ['gb-eng-enf', 'gb-eng-hry', 'gb-eng-hck', 'gb-eng-isl', 'gb-eng-cmd', 'gb-eng-hrw', 'gb-eng-hil', 'gb-eng-ben', 'gb-eng-hrt'],
  'gb-eng-enf': ['gb-eng-bne', 'gb-eng-hry', 'gb-eng-hrt', 'gb-eng-wft'],
  'gb-eng-hry': ['gb-eng-enf', 'gb-eng-bne', 'gb-eng-hck', 'gb-eng-isl', 'gb-eng-cmd'],
  'gb-eng-hck': ['gb-eng-hry', 'gb-eng-isl', 'gb-eng-lnd', 'gb-eng-twh', 'gb-eng-nwm'],
  'gb-eng-hrw': ['gb-eng-bne', 'gb-eng-hil', 'gb-eng-ben', 'gb-eng-eal'],
  // West
  'gb-eng-ben': ['gb-eng-hrw', 'gb-eng-hry', 'gb-eng-bne', 'gb-eng-cmd', 'gb-eng-kec', 'gb-eng-hns', 'gb-eng-eal', 'gb-eng-hil'],
  'gb-eng-eal': ['gb-eng-hil', 'gb-eng-ben', 'gb-eng-hns', 'gb-eng-kec', 'gb-eng-hmf', 'gb-eng-ric', 'gb-eng-hrw'],
  'gb-eng-hil': ['gb-eng-hrw', 'gb-eng-ben', 'gb-eng-eal', 'gb-eng-hns', 'gb-eng-bne'],
  'gb-eng-hns': ['gb-eng-hil', 'gb-eng-ben', 'gb-eng-eal', 'gb-eng-kec', 'gb-eng-hmf', 'gb-eng-ric'],
  'gb-eng-ric': ['gb-eng-hns', 'gb-eng-eal', 'gb-eng-hmf', 'gb-eng-mrt', 'gb-eng-ktt', 'gb-eng-sry'],
  'gb-eng-ktt': ['gb-eng-ric', 'gb-eng-mrt', 'gb-eng-stn', 'gb-eng-sry'],
  // South
  'gb-eng-wnd': ['gb-eng-hmf', 'gb-eng-mrt', 'gb-eng-lbh', 'gb-eng-swk', 'gb-eng-wsm', 'gb-eng-sry'],
  'gb-eng-mrt': ['gb-eng-hmf', 'gb-eng-ric', 'gb-eng-ktt', 'gb-eng-stn', 'gb-eng-cry', 'gb-eng-lbh', 'gb-eng-wnd', 'gb-eng-sry'],
  'gb-eng-lbh': ['gb-eng-wnd', 'gb-eng-mrt', 'gb-eng-stn', 'gb-eng-cry', 'gb-eng-lew', 'gb-eng-swk', 'gb-eng-wsm', 'gb-eng-sry'],
  'gb-eng-swk': ['gb-eng-lnd', 'gb-eng-twh', 'gb-eng-lew', 'gb-eng-lbh', 'gb-eng-wnd', 'gb-eng-wsm'],
  'gb-eng-lew': ['gb-eng-swk', 'gb-eng-gre', 'gb-eng-bex', 'gb-eng-bry', 'gb-eng-cry', 'gb-eng-lbh', 'gb-eng-ken', 'gb-eng-esx'],
  'gb-eng-cry': ['gb-eng-bry', 'gb-eng-lew', 'gb-eng-lbh', 'gb-eng-mrt', 'gb-eng-stn', 'gb-eng-sry', 'gb-eng-esx'],
  'gb-eng-bry': ['gb-eng-bex', 'gb-eng-gre', 'gb-eng-lew', 'gb-eng-cry', 'gb-eng-stn', 'gb-eng-ken', 'gb-eng-sry', 'gb-eng-esx'],
  'gb-eng-stn': ['gb-eng-mrt', 'gb-eng-ktt', 'gb-eng-cry', 'gb-eng-bry', 'gb-eng-sry'],
  // East/Southeast
  'gb-eng-twh': ['gb-eng-lnd', 'gb-eng-isl', 'gb-eng-hck', 'gb-eng-nwm', 'gb-eng-gre', 'gb-eng-swk'],
  'gb-eng-nwm': ['gb-eng-hck', 'gb-eng-twh', 'gb-eng-gre', 'gb-eng-bex', 'gb-eng-hav', 'gb-eng-rdb', 'gb-eng-wft', 'gb-eng-ess'],
  'gb-eng-gre': ['gb-eng-twh', 'gb-eng-nwm', 'gb-eng-bex', 'gb-eng-lew', 'gb-eng-swk', 'gb-eng-ken'],
  'gb-eng-bex': ['gb-eng-gre', 'gb-eng-nwm', 'gb-eng-hav', 'gb-eng-lew', 'gb-eng-bry', 'gb-eng-ken'],
  'gb-eng-hav': ['gb-eng-bex', 'gb-eng-nwm', 'gb-eng-rdb', 'gb-eng-bdg', 'gb-eng-ess'],
  'gb-eng-rdb': ['gb-eng-hav', 'gb-eng-nwm', 'gb-eng-wft', 'gb-eng-bdg', 'gb-eng-ess'],
  'gb-eng-bdg': ['gb-eng-hav', 'gb-eng-rdb', 'gb-eng-wft', 'gb-eng-ess'],
  'gb-eng-wft': ['gb-eng-rdb', 'gb-eng-nwm', 'gb-eng-hck', 'gb-eng-bdg', 'gb-eng-enf', 'gb-eng-hrt', 'gb-eng-ess'],
  // Metropolitan districts — cross-group borders only (within-group handled by getNeighbors)
  // Greater Manchester outer borders
  'gb-eng-man': ['gb-eng-lan'],
  'gb-eng-bol': ['gb-eng-lan'],
  'gb-eng-bur': ['gb-eng-lan'],
  'gb-eng-rch': ['gb-eng-lan'],
  'gb-eng-old': ['gb-eng-lan'],
  'gb-eng-wgn': ['gb-eng-lan', 'gb-eng-kwl', 'gb-eng-shn'],
  'gb-eng-skp': ['gb-eng-che', 'gb-eng-tam'],
  'gb-eng-trf': ['gb-eng-wrt'],
  'gb-eng-slf': ['gb-eng-lan'],
  'gb-eng-tam': ['gb-eng-shf', 'gb-eng-skp'],
  // Merseyside outer borders
  'gb-eng-liv': ['gb-eng-lan'],
  'gb-eng-sft': ['gb-eng-lan'],
  'gb-eng-kwl': ['gb-eng-lan', 'gb-eng-wgn'],
  'gb-eng-shn': ['gb-eng-wgn', 'gb-eng-hal'],
  'gb-eng-wrl': ['gb-eng-chw', 'gb-eng-hal'],
  // West Midlands outer borders
  'gb-eng-bir': ['gb-eng-sts', 'gb-eng-war', 'gb-eng-wor'],
  'gb-eng-cov': ['gb-eng-war'],
  'gb-eng-sol': ['gb-eng-war', 'gb-eng-wor'],
  'gb-eng-dud': ['gb-eng-wor', 'gb-eng-sts', 'gb-eng-war'],
  'gb-eng-saw': ['gb-eng-sts'],
  'gb-eng-wll': ['gb-eng-sts'],
  'gb-eng-wlv': ['gb-eng-sts'],
  // West Yorkshire outer borders
  'gb-eng-brd': ['gb-eng-nyk', 'gb-eng-lan'],
  'gb-eng-lds': ['gb-eng-nyk', 'gb-eng-yor'],
  'gb-eng-cld': ['gb-eng-lan'],
  'gb-eng-kir': [],
  'gb-eng-wkf': ['gb-eng-nyk', 'gb-eng-dnc'],
  // South Yorkshire outer borders
  'gb-eng-shf': ['gb-eng-nyk', 'gb-eng-dby', 'gb-eng-ntt', 'gb-eng-tam'],
  'gb-eng-rot': ['gb-eng-nyk', 'gb-eng-dby', 'gb-eng-ntt'],
  'gb-eng-dnc': ['gb-eng-nyk', 'gb-eng-ntt', 'gb-eng-lin', 'gb-eng-wkf'],
  'gb-eng-bns': ['gb-eng-nyk', 'gb-eng-dby'],
  // Tyne and Wear outer borders
  'gb-eng-net': ['gb-eng-nbl', 'gb-eng-dur'],
  'gb-eng-nty': ['gb-eng-nbl'],
  'gb-eng-gat': ['gb-eng-dur'],
  'gb-eng-snd': ['gb-eng-dur'],
  'gb-eng-sty': ['gb-eng-dur'],
  // ── Scotland — short codes adjacency ─────────────────────────────────────────
  'sco': ['edi', 'gla', 'fal', 'cen', 'fif', 'dun', 'per', 'tay'],
  'edi': ['fal', 'cen', 'fif'],
  'gla': ['fal', 'cen'],
  'fal': ['edi', 'gla', 'cen', 'fif'],
  'cen': ['edi', 'gla', 'fal', 'fif', 'per', 'tay', 'dun'],
  'fif': ['edi', 'fal', 'cen', 'tay', 'per', 'dun'],
  'tay': ['cen', 'fif', 'per', 'dun'],
  'dun': ['tay', 'per', 'fif', 'cen'],
  'per': ['cen', 'tay', 'dun', 'fif'],
  // ── Wales ────────────────────────────────────────────────────────────────────
  'gb-wls-agy': ['gb-wls-gwn'],
  'gb-wls-bge': ['gb-wls-rct', 'gb-wls-vgl', 'gb-wls-cay', 'gb-wls-ntl'],
  'gb-wls-bgw': ['gb-wls-tof', 'gb-wls-cay', 'gb-wls-mty', 'gb-wls-pow', 'gb-wls-mon'],
  'gb-wls-cay': ['gb-wls-bge', 'gb-wls-rct', 'gb-wls-mty', 'gb-wls-bgw', 'gb-wls-tof', 'gb-wls-nwp'],
  'gb-wls-cgn': ['gb-wls-pow', 'gb-wls-gwn', 'gb-wls-cmn', 'gb-wls-pem'],
  'gb-wls-cmn': ['gb-wls-pow', 'gb-wls-cgn', 'gb-wls-pem', 'gb-wls-swa', 'gb-wls-ntl'],
  'gb-wls-crf': ['gb-wls-vgl', 'gb-wls-rct', 'gb-wls-cay', 'gb-wls-mon', 'gb-wls-nwp'],
  'gb-wls-cwy': ['gb-wls-den', 'gb-wls-gwn', 'gb-wls-pow'],
  'gb-wls-den': ['gb-wls-cwy', 'gb-wls-fln', 'gb-wls-pow', 'gb-wls-wrx', 'gb-eng-chw'],
  'gb-wls-fln': ['gb-wls-den', 'gb-wls-wrx', 'gb-wls-cwy', 'gb-eng-chw', 'gb-eng-che'],
  'gb-wls-gwn': ['gb-wls-agy', 'gb-wls-cwy', 'gb-wls-cgn', 'gb-wls-pow', 'gb-wls-cmn'],
  'gb-wls-mon': ['gb-wls-bgw', 'gb-wls-tof', 'gb-wls-nwp', 'gb-wls-crf', 'gb-wls-pow', 'gb-eng-hef', 'gb-eng-gls'],
  'gb-wls-mty': ['gb-wls-bgw', 'gb-wls-cay', 'gb-wls-rct', 'gb-wls-pow'],
  'gb-wls-ntl': ['gb-wls-cay', 'gb-wls-bge', 'gb-wls-swa', 'gb-wls-cmn', 'gb-wls-rct'],
  'gb-wls-nwp': ['gb-wls-mon', 'gb-wls-tof', 'gb-wls-cay', 'gb-wls-crf'],
  'gb-wls-pem': ['gb-wls-cmn', 'gb-wls-cgn'],
  'gb-wls-pow': ['gb-wls-cwy', 'gb-wls-den', 'gb-wls-gwn', 'gb-wls-cgn', 'gb-wls-cmn', 'gb-wls-mty', 'gb-wls-bgw', 'gb-wls-mon', 'gb-wls-tof', 'gb-wls-wrx', 'gb-eng-shr', 'gb-eng-hef', 'gb-eng-wor', 'gb-eng-gls'],
  'gb-wls-rct': ['gb-wls-cay', 'gb-wls-bge', 'gb-wls-vgl', 'gb-wls-crf', 'gb-wls-mty', 'gb-wls-ntl'],
  'gb-wls-swa': ['gb-wls-ntl', 'gb-wls-cmn'],
  'gb-wls-tof': ['gb-wls-bgw', 'gb-wls-cay', 'gb-wls-nwp', 'gb-wls-mon', 'gb-wls-pow'],
  'gb-wls-vgl': ['gb-wls-crf', 'gb-wls-rct', 'gb-wls-bge'],
  'gb-wls-wrx': ['gb-wls-fln', 'gb-wls-den', 'gb-wls-pow', 'gb-eng-shr', 'gb-eng-chw', 'gb-eng-che'],
  // ioi has no neighbours in this scheme
};

/**
 * BFS over REGION_ADJACENCY + group membership to find all region codes
 * reachable within `hops` steps from `code`. Returns neighbor codes only
 * (does not include `code` itself).
 */
export function getNeighbors(
  code: string,
  hops: number,
  regionRelationships: Record<string, { group?: string }>,
  geographicGroups: Record<string, string[]>,
): string[] {
  if (hops <= 0) return [];

  const visited = new Set([code]);
  let frontier = [code];

  for (let h = 0; h < hops; h++) {
    const next: string[] = [];
    for (const cur of frontier) {
      // explicit adjacency
      for (const nb of REGION_ADJACENCY[cur] ?? []) {
        if (!visited.has(nb)) { visited.add(nb); next.push(nb); }
      }
      // implicit group adjacency — all members of the same group are adjacent
      const grp = regionRelationships[cur]?.group;
      if (grp) {
        for (const nb of geographicGroups[grp] ?? []) {
          if (!visited.has(nb)) { visited.add(nb); next.push(nb); }
        }
      }
    }
    frontier = next;
  }

  visited.delete(code);
  return [...visited];
}
